language: go
go:
- 1.6
- 1.5

before_install:
- cp .netrc ~
- chmod 600 .netrc
- go get golang.org/x/tools/cmd/vet
- go get golang.org/x/tools/cmd/cover
- go get github.com/golang/lint/golint
- go get github.com/fzipp/gocyclo 

script:
  - go test -cover ./...
  - go tool vet -all .
  - gocyclo -over 10 .
