version: 2
jobs:
  test:
    docker:
      - image: cimg/go:1.17
    working_directory: ~/go/src/github.com/ingresso-group/gojsonrpc
    steps:
      - checkout
      - run:
          name: setup
          command: make setup
      - run:
          name: test v1
          command: cd v1 ; go test ./...
      - run:
          name: test v2
          command: cd v2 ; go test ./...
workflows:
  version: 2 
  test:
    jobs:
      - test
